### ISSUE TITLE
npm install leads to warnings

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [aickin/shrink-ray#5]
npm install throws the below warnings. the reason is the dependency 'iltorb'.
Even in the current version 1.0.13 this is not yet fixed there. Maybe you can address this issue to them and then make a dependency bump for your module. TIA!

`> iltorb@1.0.13 install /home/kai/git/testpricing/node_modules/iltorb
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
`

**Comment by KaiSchwarz-cnic** [comment]
https://github.com/nodejs/node-gyp/issues/942
https://github.com/creationix/nvm/issues/1429

**Comment by aickin** [comment]
Thanks for the issue!

I can't repro this, and from creationix/nvm#1429, it seems like it's an issue in nvm, right? Closing this issue, as I think creationix/nvm#1429 should in theory fix this. Thanks!
